# Generated by Django 2.1.7 on 2020-02-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ('name',), 'verbose_name': 'promocion', 'verbose_name_plural': 'promociones'},
        ),
        migrations.AddField(
            model_name='promotion',
            name='link',
            field=models.URLField(default=' ', verbose_name='URL'),
        ),
    ]
